### ISSUE TITLE
No logo, no image displayed.

### ISSUE THREAD

**Issue by q1erty** [q1erty/first-website#1]
Hello. There are no 
<img width="960" alt="no-logo-displaed" src="https://user-images.githubusercontent.com/83899354/173249351-7706239a-36dc-42ea-99b6-87bd20cc3ce0.png">
<img width="960" alt="no-image-displaed" src="https://user-images.githubusercontent.com/83899354/173249357-0a6e8ae1-10be-4dbc-b1f3-e163f42f3e76.png">
logo and image displayed on my Pages site  https://q1erty.github.io/first-website/. Meanwhile the logo image was successfully uploaded as my Github avatar.

**Comment by SCOTTY0101** [comment]
Change file name from  "my-logo.JPG" and "my-pet.JPG" to "my-logo.jpg" 
 and "my-pet.jpg" in file uploads. 

Delete and upload new files with lowercase ".jpg"

UPPERCASE and lowercase file name issue  .JPG to .jpg 

надеюсь, это помогло

**Comment by q1erty** [comment]
> Change file name from "my-logo.JPG" and "my-pet.JPG" to "my-logo.jpg" and "my-pet.jpg" in file uploads.
> 
> Delete and upload new files with lowercase ".jpg"
> 
> UPPERCASE and lowercase file name issue .JPG to .jpg
> 
> надеюсь, это помогло

Thank you for the answer. I found the way to make it cause it is not that easy for me. https://www.vishalon.net/blog/4-ways-to-change-the-file-extension-to-uppercaselowercase-in-windows#:~:text=Within%20Windows%20Explorer%2C%20right%20click,change%20it%20to%20uppercase%2Flowercase.
